on:
  workflow_call:
    inputs:      
      factoryRepo:
        type: string
        required: true        
      factoryBranch:
        type: string
        required: true
      devPipeline:
        type: string
        required: true

concurrency: 1
jobs:
  buildCode:    
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 3        
    steps:
      - name: Show sample
        run: |-
          echo "Factory Repo: ${{github.event.inputs.factoryRepo}}"
          echo "Factory Branch: ${{github.event.inputs.factoryBranch}}"
          echo "Dev Pipeline: ${{github.event.inputs.devPipeline}}"